// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/Presbyter/services/protobuf"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	CreateAccountEndpoint endpoint.Endpoint
	AddGroupEndpoint      endpoint.Endpoint
	DeleteGroupEndpoint   endpoint.Endpoint
	AddFriendEndpoint     endpoint.Endpoint
	DeleteFriendEndpoint  endpoint.Endpoint
}

// Endpoints

func (e Endpoints) CreateAccount(ctx context.Context, in *pb.CreateAccountReq) (*pb.CreateAccountResp, error) {
	response, err := e.CreateAccountEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.CreateAccountResp), nil
}

func (e Endpoints) AddGroup(ctx context.Context, in *pb.AddGroupReq) (*pb.AddGroupResp, error) {
	response, err := e.AddGroupEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.AddGroupResp), nil
}

func (e Endpoints) DeleteGroup(ctx context.Context, in *pb.DeleteGroupReq) (*pb.Empty, error) {
	response, err := e.DeleteGroupEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Empty), nil
}

func (e Endpoints) AddFriend(ctx context.Context, in *pb.AddFriendReq) (*pb.Empty, error) {
	response, err := e.AddFriendEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Empty), nil
}

func (e Endpoints) DeleteFriend(ctx context.Context, in *pb.DeleteFriendReq) (*pb.Empty, error) {
	response, err := e.DeleteFriendEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Empty), nil
}

// Make Endpoints

func MakeCreateAccountEndpoint(s pb.ImServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.CreateAccountReq)
		v, err := s.CreateAccount(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAddGroupEndpoint(s pb.ImServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AddGroupReq)
		v, err := s.AddGroup(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeDeleteGroupEndpoint(s pb.ImServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.DeleteGroupReq)
		v, err := s.DeleteGroup(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAddFriendEndpoint(s pb.ImServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AddFriendReq)
		v, err := s.AddFriend(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeDeleteFriendEndpoint(s pb.ImServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.DeleteFriendReq)
		v, err := s.DeleteFriend(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"CreateAccount": {},
		"AddGroup":      {},
		"DeleteGroup":   {},
		"AddFriend":     {},
		"DeleteFriend":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "CreateAccount" {
			e.CreateAccountEndpoint = middleware(e.CreateAccountEndpoint)
		}
		if inc == "AddGroup" {
			e.AddGroupEndpoint = middleware(e.AddGroupEndpoint)
		}
		if inc == "DeleteGroup" {
			e.DeleteGroupEndpoint = middleware(e.DeleteGroupEndpoint)
		}
		if inc == "AddFriend" {
			e.AddFriendEndpoint = middleware(e.AddFriendEndpoint)
		}
		if inc == "DeleteFriend" {
			e.DeleteFriendEndpoint = middleware(e.DeleteFriendEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"CreateAccount": {},
		"AddGroup":      {},
		"DeleteGroup":   {},
		"AddFriend":     {},
		"DeleteFriend":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "CreateAccount" {
			e.CreateAccountEndpoint = middleware("CreateAccount", e.CreateAccountEndpoint)
		}
		if inc == "AddGroup" {
			e.AddGroupEndpoint = middleware("AddGroup", e.AddGroupEndpoint)
		}
		if inc == "DeleteGroup" {
			e.DeleteGroupEndpoint = middleware("DeleteGroup", e.DeleteGroupEndpoint)
		}
		if inc == "AddFriend" {
			e.AddFriendEndpoint = middleware("AddFriend", e.AddFriendEndpoint)
		}
		if inc == "DeleteFriend" {
			e.DeleteFriendEndpoint = middleware("DeleteFriend", e.DeleteFriendEndpoint)
		}
	}
}
