// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/Presbyter/services/protobuf"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	GetCodeEndpoint      endpoint.Endpoint
	GetTokenEndpoint     endpoint.Endpoint
	RefreshTokenEndpoint endpoint.Endpoint
	BanTokenEndpoint     endpoint.Endpoint
}

// Endpoints

func (e Endpoints) GetCode(ctx context.Context, in *pb.GetCodeReq) (*pb.GetCodeResp, error) {
	response, err := e.GetCodeEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetCodeResp), nil
}

func (e Endpoints) GetToken(ctx context.Context, in *pb.GetTokenReq) (*pb.GetTokenResp, error) {
	response, err := e.GetTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetTokenResp), nil
}

func (e Endpoints) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	response, err := e.RefreshTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.RefreshTokenResp), nil
}

func (e Endpoints) BanToken(ctx context.Context, in *pb.BanTokenReq) (*pb.Empty, error) {
	response, err := e.BanTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Empty), nil
}

// Make Endpoints

func MakeGetCodeEndpoint(s pb.AuthServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetCodeReq)
		v, err := s.GetCode(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetTokenEndpoint(s pb.AuthServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetTokenReq)
		v, err := s.GetToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeRefreshTokenEndpoint(s pb.AuthServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.RefreshTokenReq)
		v, err := s.RefreshToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeBanTokenEndpoint(s pb.AuthServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.BanTokenReq)
		v, err := s.BanToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"GetCode":      {},
		"GetToken":     {},
		"RefreshToken": {},
		"BanToken":     {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetCode" {
			e.GetCodeEndpoint = middleware(e.GetCodeEndpoint)
		}
		if inc == "GetToken" {
			e.GetTokenEndpoint = middleware(e.GetTokenEndpoint)
		}
		if inc == "RefreshToken" {
			e.RefreshTokenEndpoint = middleware(e.RefreshTokenEndpoint)
		}
		if inc == "BanToken" {
			e.BanTokenEndpoint = middleware(e.BanTokenEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"GetCode":      {},
		"GetToken":     {},
		"RefreshToken": {},
		"BanToken":     {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetCode" {
			e.GetCodeEndpoint = middleware("GetCode", e.GetCodeEndpoint)
		}
		if inc == "GetToken" {
			e.GetTokenEndpoint = middleware("GetToken", e.GetTokenEndpoint)
		}
		if inc == "RefreshToken" {
			e.RefreshTokenEndpoint = middleware("RefreshToken", e.RefreshTokenEndpoint)
		}
		if inc == "BanToken" {
			e.BanTokenEndpoint = middleware("BanToken", e.BanTokenEndpoint)
		}
	}
}
