// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/Presbyter/services/protobuf"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC UserServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.UserServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// user

		userinfo: grpctransport.NewServer(
			endpoints.UserInfoEndpoint,
			DecodeGRPCUserInfoRequest,
			EncodeGRPCUserInfoResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the UserServer interface
type grpcServer struct {
	userinfo grpctransport.Handler
}

// Methods for grpcServer to implement UserServer interface

func (s *grpcServer) UserInfo(ctx context.Context, req *pb.UserInfoReq) (*pb.UserInfoResp, error) {
	_, rep, err := s.userinfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.UserInfoResp), nil
}

// Server Decode

// DecodeGRPCUserInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC userinfo request to a user-domain userinfo request. Primarily useful in a server.
func DecodeGRPCUserInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UserInfoReq)
	return req, nil
}

// Server Encode

// EncodeGRPCUserInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain userinfo response to a gRPC userinfo reply. Primarily useful in a server.
func EncodeGRPCUserInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.UserInfoResp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
